version: 2
jobs:
  cache_and_run_tests:
    docker:
      - image: circleci/python:3.6
    resource_class: medium
    working_directory: ~/adaptnlp
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pip install .
      - run:
          name: run tests
          command: |
            python3 -m pytest
  deploy_doc:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/adaptnlp
    steps:
      - checkout
      - run: pip install .
      - run: pip install -r docs/requirements.txt
      - run:
          name: install mkdocs an deploy to gh-pages
          command: |
            python -m mkdocs gh-deploy

workflow_filters: &workflow_filters
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  build_and_test:
    jobs:
      - cache_and_run_tests
      - deploy_doc
